.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2022 kokoye2007 <kokoye2007@gmail.com>,
.TH FORTUNE-DHP 1 "April 20, 2022"

.SH NAME
fortune-dhp \- Dhammapada multi language files for fortune

.SH SYNOPSIS
.B fortune-dhp

.SH DESCRIPTION
\fIfortune-dhp\fR is a simple shell script that invokes \fIfortune\fR with dhammapada
multiple language files and language set.

.SS Options
The options are as follows:
.TP

.B \-l, \-\-language	[ CC | CC_AUTHOR ]
Choose from available dhammapada lists of language code. eg. en or en_buddharakkhita
.TP

.B \-h \-\-help 
option for more information. 
.TP

.B \-r, \-\-regex	[ pattern | number ]
Print out all dhammapada fortunes which match the basic regular expression
.IR pattern .
The syntax of these expressions depends on how your system defines 
.BI re_comp "(3) or "regcomp (3),
but it should nevertheless be similar to the syntax used in 
.BI grep (1).
.sp
.TP


.B \-b, \-\-box		[ z | n | k | p | a ]
Show with GUI - 
 z - zenity
 n - notify-send
 k - kdialog
 p - kdialog popup 
 a - auto detect
.TP

.B \-a, \-b a
Auto detect Desktop Envirement  
.TP

.SH DATAFILE
.TP
.I /usr/share/games/fortunes/dhp
Dhammapada fortune in many languages, both same language in difference author.

.SH SEE ALSO
.BR fortune "(1), " re_comp "(3), " regcomp "(3), " strfile "(1), "
.BR unstr (1)



.SH AUTHOR
fortune-dhp was data from SuttaCentral
.IP
Copyright SuttaCentral - sujato <sujato@gmail.com>
.PP
This manual page was written by kokoye2007 <kokoye2007@gmail.com> for Debian, and may be used by others.
