#!/bin/bash
set -e

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
RESET=$(tput sgr0)
BOLD=$(tput bold)

FORTUNE="$(which fortune)"
[ -x "$FORTUNE" ] || ( echo "E: Please install package 'fortune-mod'."; false )

data_dir=/usr/share/games/fortunes/

dhp_list=$(find $data_dir -type f  -name "*-dhp" | cut -d'/' -f6 | cut -f1 -d- | sort)
DDHPD=$(find $data_dir -type f  -name "*-dhp" | cut -d'/' -f6 | sort)

dhp_l10n(){
	cat <<EOF

${BOLD} LANGUAGE ${RESET}

  ${GREEN}my${RESET}    Burmese
  ${GREEN}ca${RESET}    Catalan         
        ${BLUE}ca_jambudipa | ca_durall${RESET}
  ${GREEN}cs${RESET}    Czech
  ${GREEN}nl${RESET}    Dutch
        ${BLUE}nl_dubois | nl_loosbroek ${RESET}
  ${GREEN}en${RESET}    English 
        ${BLUE}en_anandajoti | en_buddharakkhita
        en_feldmeier${RESET}
  ${GREEN}fr${RESET}    French
  ${GREEN}de${RESET}    German
  ${GREEN}he${RESET}    Hebrew
  ${GREEN}hu${RESET}    Hungarian
  ${GREEN}it${RESET}    Italian
  ${GREEN}ja${RESET}    Japanese
  ${GREEN}mr${RESET}    Marathi
  ${GREEN}no${RESET}    Norwegian
  ${GREEN}pl${RESET}    Polish
  ${GREEN}pt${RESET}    Portuguese
        ${BLUE}pl_becker | pt_beisert
        pt_guimaraes ${RESET}
  ${GREEN}si${RESET}    Singhalese
  ${GREEN}sl${RESET}    Slovenian
  ${GREEN}es${RESET}    Spanish
  ${GREEN}ta${RESET}    Tamil

EOF
exit
}

# HELP MENU
usage(){
cat <<EOF

Usage:	${BOLD}$(basename "${BASH_SOURCE[0]}")${RESET} [-h] [-c ${GREEN}en|ca|it${RESET}]  
	[-r ${GREEN}search-content | ID ${RESET}] [-z]

${RED}##################################################${RESET}

-l, --language		Use language code XX | en 
-h, --help		Print this help and exit
-r, --regex		Search pattern and number
-z, --zenity		GUI with Zenity

${RED}##################################################${RESET}

EOF
dhp_l10n
}

# Main 
main_menu(){

	DHPD=''
	dhp_regex=0
	dhp_language=0
	dhp_zenity=0
	dhp_l=''

	while :; do
		case "${1-}" in
                -h | --help) usage ;;
		-z | --zenity)
			dhp_zenity=1
			;;
		-r | --regex) 
			dhp_regex=1 
			dhp_r="${2-}"
                        shift
                        ;;
		-l | --language)
			dhp_language=1
			dhp_l="${2-}"
                        shift
                        ;;
                -?*) 
			echo "Unknown option: $1" 
			exit ;;
                *) break ;;
                esac
                shift
        done

# Regex to Fortune
if [ ${dhp_regex} -ne 0 ]; then
	DHP_SEARCH="-m $dhp_r"
fi

# Check Language Input
if [ ${dhp_language} -ne 0 ]; then
	if  echo "${dhp_list[*]}" | grep -q "$dhp_l" ; then
		DHPD=$(find $data_dir -type f  -name "${dhp_l}*-dhp" | cut -d'/' -f6 | sort)
		[[ -z  $DHPD ]] && usage
	else
		dhp_l10n
	fi
else

# Check System LANG
if [ -n "$LC_ALL" ]; then
	LANG="$LC_ALL"
fi

# Take Language
LANG_CODE=$(echo "$LANG" | cut -d_ -f1)
	case "$LANG_CODE" in
	  cs | de | es | fr | he | hu | it | ja | mr | my | no | si | sl | ta ) 
	  	DHPD=$LANG_CODE-dhp
	  	;;
	  ca | en | nl | pt )
	  	DHPD="$(find $data_dir -type f  -name "$LANG_CODE*-dhp" | cut -d'/' -f6 | sort)"
	  	;;
	  *)
	  	DHPD="$DDHPD"
	  	;;
	  esac
fi

return 0
}

main_menu "$@"

# Zenity or Terminal
if [ ${dhp_zenity} -ne 0 ]; then
	zenity --info --title="Dhammapada" --no-wrap --icon-name=dhp-lotus --text="$($FORTUNE $DHPD $DHP_SEARCH)" --timeout=10
else
	$FORTUNE $DHPD $DHP_SEARCH
fi
